// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpkm66/checkin/staff/v1/staff.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddEventToUser
type AddEventToUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StaffUserId string `protobuf:"bytes,1,opt,name=staff_user_id,json=staffUserId,proto3" json:"staff_user_id,omitempty"`
	UserId      string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId     string `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *AddEventToUserRequest) Reset() {
	*x = AddEventToUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEventToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventToUserRequest) ProtoMessage() {}

func (x *AddEventToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventToUserRequest.ProtoReflect.Descriptor instead.
func (*AddEventToUserRequest) Descriptor() ([]byte, []int) {
	return file_rpkm66_checkin_staff_v1_staff_proto_rawDescGZIP(), []int{0}
}

func (x *AddEventToUserRequest) GetStaffUserId() string {
	if x != nil {
		return x.StaffUserId
	}
	return ""
}

func (x *AddEventToUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddEventToUserRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type AddEventToUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AddEventToUserResponse) Reset() {
	*x = AddEventToUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddEventToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventToUserResponse) ProtoMessage() {}

func (x *AddEventToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventToUserResponse.ProtoReflect.Descriptor instead.
func (*AddEventToUserResponse) Descriptor() ([]byte, []int) {
	return file_rpkm66_checkin_staff_v1_staff_proto_rawDescGZIP(), []int{1}
}

func (x *AddEventToUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GenerateSignInToken
type GenerateSignInTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StaffUserId string `protobuf:"bytes,1,opt,name=staff_user_id,json=staffUserId,proto3" json:"staff_user_id,omitempty"`
	EventId     string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EndAt       int64  `protobuf:"varint,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
}

func (x *GenerateSignInTokenRequest) Reset() {
	*x = GenerateSignInTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSignInTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignInTokenRequest) ProtoMessage() {}

func (x *GenerateSignInTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignInTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateSignInTokenRequest) Descriptor() ([]byte, []int) {
	return file_rpkm66_checkin_staff_v1_staff_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateSignInTokenRequest) GetStaffUserId() string {
	if x != nil {
		return x.StaffUserId
	}
	return ""
}

func (x *GenerateSignInTokenRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GenerateSignInTokenRequest) GetEndAt() int64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

type GenerateSignInTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GenerateSignInTokenResponse) Reset() {
	*x = GenerateSignInTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateSignInTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSignInTokenResponse) ProtoMessage() {}

func (x *GenerateSignInTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSignInTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateSignInTokenResponse) Descriptor() ([]byte, []int) {
	return file_rpkm66_checkin_staff_v1_staff_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateSignInTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// IsStaff
type IsStaffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StaffId string `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
}

func (x *IsStaffRequest) Reset() {
	*x = IsStaffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsStaffRequest) ProtoMessage() {}

func (x *IsStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsStaffRequest.ProtoReflect.Descriptor instead.
func (*IsStaffRequest) Descriptor() ([]byte, []int) {
	return file_rpkm66_checkin_staff_v1_staff_proto_rawDescGZIP(), []int{4}
}

func (x *IsStaffRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type IsStaffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsStaff bool `protobuf:"varint,1,opt,name=is_staff,json=isStaff,proto3" json:"is_staff,omitempty"`
}

func (x *IsStaffResponse) Reset() {
	*x = IsStaffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsStaffResponse) ProtoMessage() {}

func (x *IsStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsStaffResponse.ProtoReflect.Descriptor instead.
func (*IsStaffResponse) Descriptor() ([]byte, []int) {
	return file_rpkm66_checkin_staff_v1_staff_proto_rawDescGZIP(), []int{5}
}

func (x *IsStaffResponse) GetIsStaff() bool {
	if x != nil {
		return x.IsStaff
	}
	return false
}

var File_rpkm66_checkin_staff_v1_staff_proto protoreflect.FileDescriptor

var file_rpkm66_checkin_staff_v1_staff_proto_rawDesc = []byte{
	0x0a, 0x23, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x36, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e,
	0x2f, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x36, 0x2e, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x22, 0x6f,
	0x0a, 0x15, 0x41, 0x64, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x73, 0x74, 0x61, 0x66, 0x66, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x32, 0x0a, 0x16, 0x41, 0x64, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x72, 0x0a, 0x1a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53,
	0x69, 0x67, 0x6e, 0x49, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x66, 0x66, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x22, 0x33, 0x0a, 0x1b, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2b, 0x0a, 0x0e,
	0x49, 0x73, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x74, 0x61, 0x66, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x0f, 0x49, 0x73, 0x53,
	0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x69, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x66, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x69, 0x73, 0x53, 0x74, 0x61, 0x66, 0x66, 0x32, 0xe8, 0x02, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2e, 0x2e, 0x72, 0x70, 0x6b,
	0x6d, 0x36, 0x36, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x72, 0x70, 0x6b,
	0x6d, 0x36, 0x36, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x82, 0x01,
	0x0a, 0x13, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x33, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x36, 0x2e, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x72, 0x70, 0x6b,
	0x6d, 0x36, 0x36, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x6e, 0x49, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5e, 0x0a, 0x07, 0x49, 0x73, 0x53, 0x74, 0x61, 0x66, 0x66, 0x12, 0x27, 0x2e,
	0x72, 0x70, 0x6b, 0x6d, 0x36, 0x36, 0x2e, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x73,
	0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x73, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x36, 0x2e,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x2e, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x73, 0x53, 0x74, 0x61, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x72, 0x70, 0x6b, 0x6d, 0x36, 0x36, 0x2f, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x69, 0x6e, 0x2f, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpkm66_checkin_staff_v1_staff_proto_rawDescOnce sync.Once
	file_rpkm66_checkin_staff_v1_staff_proto_rawDescData = file_rpkm66_checkin_staff_v1_staff_proto_rawDesc
)

func file_rpkm66_checkin_staff_v1_staff_proto_rawDescGZIP() []byte {
	file_rpkm66_checkin_staff_v1_staff_proto_rawDescOnce.Do(func() {
		file_rpkm66_checkin_staff_v1_staff_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpkm66_checkin_staff_v1_staff_proto_rawDescData)
	})
	return file_rpkm66_checkin_staff_v1_staff_proto_rawDescData
}

var file_rpkm66_checkin_staff_v1_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rpkm66_checkin_staff_v1_staff_proto_goTypes = []interface{}{
	(*AddEventToUserRequest)(nil),       // 0: rpkm66.checkin.staff.v1.AddEventToUserRequest
	(*AddEventToUserResponse)(nil),      // 1: rpkm66.checkin.staff.v1.AddEventToUserResponse
	(*GenerateSignInTokenRequest)(nil),  // 2: rpkm66.checkin.staff.v1.GenerateSignInTokenRequest
	(*GenerateSignInTokenResponse)(nil), // 3: rpkm66.checkin.staff.v1.GenerateSignInTokenResponse
	(*IsStaffRequest)(nil),              // 4: rpkm66.checkin.staff.v1.IsStaffRequest
	(*IsStaffResponse)(nil),             // 5: rpkm66.checkin.staff.v1.IsStaffResponse
}
var file_rpkm66_checkin_staff_v1_staff_proto_depIdxs = []int32{
	0, // 0: rpkm66.checkin.staff.v1.StaffService.AddEventToUser:input_type -> rpkm66.checkin.staff.v1.AddEventToUserRequest
	2, // 1: rpkm66.checkin.staff.v1.StaffService.GenerateSignInToken:input_type -> rpkm66.checkin.staff.v1.GenerateSignInTokenRequest
	4, // 2: rpkm66.checkin.staff.v1.StaffService.IsStaff:input_type -> rpkm66.checkin.staff.v1.IsStaffRequest
	1, // 3: rpkm66.checkin.staff.v1.StaffService.AddEventToUser:output_type -> rpkm66.checkin.staff.v1.AddEventToUserResponse
	3, // 4: rpkm66.checkin.staff.v1.StaffService.GenerateSignInToken:output_type -> rpkm66.checkin.staff.v1.GenerateSignInTokenResponse
	5, // 5: rpkm66.checkin.staff.v1.StaffService.IsStaff:output_type -> rpkm66.checkin.staff.v1.IsStaffResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpkm66_checkin_staff_v1_staff_proto_init() }
func file_rpkm66_checkin_staff_v1_staff_proto_init() {
	if File_rpkm66_checkin_staff_v1_staff_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEventToUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddEventToUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSignInTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateSignInTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsStaffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpkm66_checkin_staff_v1_staff_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsStaffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpkm66_checkin_staff_v1_staff_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpkm66_checkin_staff_v1_staff_proto_goTypes,
		DependencyIndexes: file_rpkm66_checkin_staff_v1_staff_proto_depIdxs,
		MessageInfos:      file_rpkm66_checkin_staff_v1_staff_proto_msgTypes,
	}.Build()
	File_rpkm66_checkin_staff_v1_staff_proto = out.File
	file_rpkm66_checkin_staff_v1_staff_proto_rawDesc = nil
	file_rpkm66_checkin_staff_v1_staff_proto_goTypes = nil
	file_rpkm66_checkin_staff_v1_staff_proto_depIdxs = nil
}
