// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: rpkm66/checkin/staff/v1/staff.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StaffService_AddEventToUser_FullMethodName      = "/rpkm66.checkin.staff.v1.StaffService/AddEventToUser"
	StaffService_GenerateSignInToken_FullMethodName = "/rpkm66.checkin.staff.v1.StaffService/GenerateSignInToken"
)

// StaffServiceClient is the client API for StaffService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StaffServiceClient interface {
	AddEventToUser(ctx context.Context, in *AddEventToUserRequest, opts ...grpc.CallOption) (*AddEventToUserResponse, error)
	GenerateSignInToken(ctx context.Context, in *GenerateSignInTokenRequest, opts ...grpc.CallOption) (*GenerateSignInTokenResponse, error)
}

type staffServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStaffServiceClient(cc grpc.ClientConnInterface) StaffServiceClient {
	return &staffServiceClient{cc}
}

func (c *staffServiceClient) AddEventToUser(ctx context.Context, in *AddEventToUserRequest, opts ...grpc.CallOption) (*AddEventToUserResponse, error) {
	out := new(AddEventToUserResponse)
	err := c.cc.Invoke(ctx, StaffService_AddEventToUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staffServiceClient) GenerateSignInToken(ctx context.Context, in *GenerateSignInTokenRequest, opts ...grpc.CallOption) (*GenerateSignInTokenResponse, error) {
	out := new(GenerateSignInTokenResponse)
	err := c.cc.Invoke(ctx, StaffService_GenerateSignInToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaffServiceServer is the server API for StaffService service.
// All implementations must embed UnimplementedStaffServiceServer
// for forward compatibility
type StaffServiceServer interface {
	AddEventToUser(context.Context, *AddEventToUserRequest) (*AddEventToUserResponse, error)
	GenerateSignInToken(context.Context, *GenerateSignInTokenRequest) (*GenerateSignInTokenResponse, error)
	mustEmbedUnimplementedStaffServiceServer()
}

// UnimplementedStaffServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStaffServiceServer struct {
}

func (UnimplementedStaffServiceServer) AddEventToUser(context.Context, *AddEventToUserRequest) (*AddEventToUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEventToUser not implemented")
}
func (UnimplementedStaffServiceServer) GenerateSignInToken(context.Context, *GenerateSignInTokenRequest) (*GenerateSignInTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateSignInToken not implemented")
}
func (UnimplementedStaffServiceServer) mustEmbedUnimplementedStaffServiceServer() {}

// UnsafeStaffServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StaffServiceServer will
// result in compilation errors.
type UnsafeStaffServiceServer interface {
	mustEmbedUnimplementedStaffServiceServer()
}

func RegisterStaffServiceServer(s grpc.ServiceRegistrar, srv StaffServiceServer) {
	s.RegisterService(&StaffService_ServiceDesc, srv)
}

func _StaffService_AddEventToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEventToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).AddEventToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_AddEventToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).AddEventToUser(ctx, req.(*AddEventToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaffService_GenerateSignInToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateSignInTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaffServiceServer).GenerateSignInToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaffService_GenerateSignInToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaffServiceServer).GenerateSignInToken(ctx, req.(*GenerateSignInTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StaffService_ServiceDesc is the grpc.ServiceDesc for StaffService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StaffService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpkm66.checkin.staff.v1.StaffService",
	HandlerType: (*StaffServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEventToUser",
			Handler:    _StaffService_AddEventToUser_Handler,
		},
		{
			MethodName: "GenerateSignInToken",
			Handler:    _StaffService_GenerateSignInToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpkm66/checkin/staff/v1/staff.proto",
}
